# Generated by Django 5.0.6 on 2026-06-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_description_product_net_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('online', 'Online'), ('presencial', 'Presencial')], default='online', max_length=20),
        ),
    ]
